services:
  jenkins-controller:
    build: ./controller
    container_name: jenkins-controller
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net

  jenkins-agent:
    build:
      context: ./agent
      args:
        DOCKER_GID: 1001   # must match host docker group GID
    container_name: jenkins-agent
    depends_on:
      - jenkins-controller
    environment:
      - JENKINS_URL=http://localhost:8081
      - JENKINS_AGENT_NAME=jenkins-agent
      - JENKINS_SECRET=30b6da28714e95752404273bddec5c2b9ce80fb8bf5ca2f22484e6b3ea00277a
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube/config:/home/jenkins/.kube/config:ro
    #networks:
    #  - jenkins-net
    network_mode: host

volumes:
  jenkins-data:

networks:
  jenkins-net:
    driver: bridge